services:
  neolink:
    #image: thirtythreeforty/neolink
    image: QuantumEntangledAndy/neolink
    container_name: neolink
    ports:
      - 48554:8554
    volumes:
      - /mnt/HDDs/App_configs/neolink/neolink.toml:/etc/neolink.toml
    restart: unless-stopped
