services:
  neolink:
    #image: thirtythreeforty/neolink
    image: QuantumEntangledAndy/neolink
    container_name: neolink
    ports:
      - 8554:8554
    volumes:
      - $PWD/neolink.toml:/etc/neolink.toml
    restart: unless-stopped
